### ISSUE TITLE
Issue with unnest_tokens inside PrepText

### ISSUE THREAD

**Issue by mbossetta** [cbail/textnets#13]
When running PrepText, I am getting the error: 

"Error in check_input(x) : 
  Input must be a character vector of any length or a list of character
  vectors, each of which has a length of 1."

This seems to be an issue with unnest_tokens inside the function, similar to the problem reported [here](https://stackoverflow.com/questions/51074426/tidyverse-unnest-tokens-does-not-work-inside-function).

I am able to use unnest_tokens outside PrepText just fine on the same data frame.

**Comment by cbail** [comment]
Hello- if this doesn't work will you please let me know:

https://github.com/cbail/textnets/issues/11

**Comment by mbossetta** [comment]
Ah, didn't see that issue. Renaming the text variable column in my data to "textvar" worked. Thanks!

**Comment by cbail** [comment]
Hey- I am unable to reproduce your problem-- are you working on mac or pc? Also, when you got the problem were you trying to rename the variable in the SOTU example data or your own dataset? In otherwords, is the problem that you had to rename your own textvar variable "textvar"? Thanks.

**Comment by mbossetta** [comment]
Hi - I'm working on a Mac, so that might be the issue (session info below).  

To clarify, I was working with my own data and had to rename the text variable from "text" to "textvar" for the function to work. I just tried with the SOTU data as well, and I get the same error. Changing sotu$sotu_text to sotu$textvar fixes the problem. 

R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

**Comment by cbail** [comment]
Huh- must be an issue with either macOS or R, since I am on older versions of both.

On May 13, 2020, at 10:37 AM, Michael Bossetta <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi - I'm working on a Mac, so that might be the issue (session info below).

To clarify, I was working with my own data and had to rename the text variable from "text" to "textvar" for the function to work. I just tried with the SOTU data as well, and I get the same error. Changing sotu$sotu_text to sotu$textvar fixes the problem.

R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3
